# Generated by Django 5.2 on 2025-11-18 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icd_code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField()),
                ('critical_level', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', help_text='Level of urgency for this disease', max_length=10)),
                ('common_symptoms', models.TextField(blank=True, help_text='Common symptoms associated with this disease', null=True)),
                ('treatment_protocol', models.TextField(blank=True, help_text='Standard treatment protocol for this disease', null=True)),
                ('treatment_guidelines', models.TextField(blank=True, help_text='Clinical treatment guidelines and recommendations', null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('verified_by', models.ForeignKey(blank=True, help_text='Doctor who verified this disease information', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_diseases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiseasePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('confidence_level', models.FloatField()),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('predicted_disease', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.disease')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseUrgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urgency_level', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=20)),
                ('time_frame_hours', models.IntegerField(help_text='Time in hours to cater the disease based on urgency level')),
                ('disease', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.disease')),
            ],
        ),
        migrations.CreateModel(
            name='HealthIssueTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_count', models.IntegerField()),
                ('period', models.DateField()),
                ('disease', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.disease')),
                ('facility', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='facilities.facility')),
            ],
        ),
        migrations.CreateModel(
            name='TotalDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_count', models.IntegerField()),
                ('period', models.DateField()),
                ('disease', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.disease')),
            ],
        ),
    ]
