# Generated by Django 5.2 on 2025-05-23 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_diseaseurgency_disease'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='critical_level',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', help_text='Level of urgency for this disease', max_length=10),
        ),
    ]
