# Generated by Django 5.2 on 2025-05-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_disease_critical_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='time_caters',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
