# Generated by Django 5.2 on 2025-05-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_disease_time_caters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='time_caters',
            field=models.FloatField(),
        ),
    ]
