# Generated by Django 5.2 on 2025-11-11 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_alter_disease_time_caters'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='icd_code',
            field=models.CharField(default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
