# Generated by Django 5.2 on 2025-11-11 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_remove_disease_time_caters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='symptoms',
        ),
    ]
