# Generated by Django 5.2 on 2025-05-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('facility_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('assigned_bhw', models.CharField(max_length=100)),
                ('address', models.TextField()),
            ],
        ),
    ]
