# Generated by Django 5.2 on 2025-05-05 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_facility_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facility',
            old_name='user',
            new_name='user_id',
        ),
    ]
