# Generated by Django 5.2 on 2025-05-06 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_rename_user_facility_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='user_id',
        ),
    ]
