# Generated by Django 5.2 on 2025-05-10 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0004_remove_facility_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='address',
        ),
        migrations.AddField(
            model_name='facility',
            name='latitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facility',
            name='longitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
