# Generated by Django 5.2 on 2025-10-27 12:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0006_facility_user_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='user_id',
        ),
        migrations.AddField(
            model_name='facility',
            name='users',
            field=models.ManyToManyField(related_name='shared_facilities', to=settings.AUTH_USER_MODEL),
        ),
    ]
