# Generated by Django 5.2 on 2025-11-06 12:46

from django.db import migrations, models


def deduplicate_facility_names(apps, schema_editor):
    Facility = apps.get_model('facilities', 'Facility')
    # Track counts case-insensitively
    seen = {}
    for facility in Facility.objects.order_by('facility_id'):
        base = (facility.name or '').strip()
        key = base.lower()
        if key == '':
            continue
        count = seen.get(key, 0)
        if count == 0:
            seen[key] = 1
            continue
        # Duplicate found; generate a unique new name with incremental suffix
        i = count + 1
        new_name = f"{base} ({i})"
        # Ensure the new name is unique even if previous duplicates existed
        while Facility.objects.filter(name__iexact=new_name).exclude(pk=facility.pk).exists():
            i += 1
            new_name = f"{base} ({i})"
        facility.name = new_name
        facility.save(update_fields=['name'])
        seen[key] = i


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0007_remove_facility_user_id_facility_users'),
    ]

    operations = [
        migrations.RunPython(deduplicate_facility_names, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
