# Generated by Django 5.2 on 2025-11-10 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0008_alter_facility_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='barangay',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
