# Generated by Django 5.2 on 2025-11-18 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('facilities', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUpVisit',
            fields=[
                ('followup_id', models.AutoField(primary_key=True, serialize=False)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bp_systolic', models.IntegerField(blank=True, null=True)),
                ('bp_diastolic', models.IntegerField(blank=True, null=True)),
                ('pulse_rate', models.IntegerField(blank=True, null=True)),
                ('respiratory_rate', models.IntegerField(blank=True, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('oxygen_saturation', models.IntegerField(blank=True, null=True)),
                ('visit_date', models.DateField()),
                ('visit_notes', models.TextField(blank=True, null=True)),
                ('current_symptoms', models.TextField(blank=True, null=True)),
                ('treatment_response', models.TextField(blank=True, null=True)),
                ('new_medications', models.TextField(blank=True, null=True)),
                ('next_followup_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medical_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_visits', to='patients.medical_history')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Follow-up Visit',
                'verbose_name_plural': 'Follow-up Visits',
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('referral_id', models.AutoField(primary_key=True, serialize=False)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bp_systolic', models.IntegerField()),
                ('bp_diastolic', models.IntegerField()),
                ('pulse_rate', models.IntegerField()),
                ('respiratory_rate', models.IntegerField()),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=4)),
                ('oxygen_saturation', models.IntegerField()),
                ('chief_complaint', models.TextField()),
                ('symptoms', models.TextField()),
                ('work_up_details', models.TextField()),
                ('ICD_code', models.CharField(blank=True, max_length=10, null=True)),
                ('disease_verified', models.BooleanField(default=False, help_text='Whether doctor verified disease information from database')),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('followup_date', models.DateField(blank=True, null=True)),
                ('initial_diagnosis', models.TextField()),
                ('final_diagnosis', models.TextField(blank=True, null=True)),
                ('referral_type', models.CharField(blank=True, choices=[('Emergency', 'Emergency'), ('Urgent', 'Urgent'), ('Routine', 'Routine'), ('Follow-up', 'Follow-up'), ('Preventive', 'Preventive')], max_length=20, null=True, verbose_name='Referral Type')),
                ('cause', models.TextField(blank=True, null=True, verbose_name='Cause')),
                ('treatments', models.TextField(blank=True, null=True, verbose_name='Treatments')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('is_smoker', models.BooleanField(default=False, verbose_name='Is Smoker')),
                ('smoking_sticks_per_day', models.IntegerField(blank=True, null=True, verbose_name='Smoking: Sticks/Packs per Day')),
                ('is_alcoholic', models.BooleanField(default=False, verbose_name='Is Alcoholic')),
                ('alcohol_bottles_per_year', models.IntegerField(blank=True, null=True, verbose_name='Alcohol: Bottles per Year')),
                ('family_planning', models.BooleanField(default=False, verbose_name='Family Planning')),
                ('family_planning_type', models.CharField(blank=True, choices=[('DMPA', 'DMPA'), ('IMPLANT', 'IMPLANT'), ('IUD', 'IUD'), ('PILLS', 'PILLS')], max_length=20, null=True, verbose_name='Family Planning Type')),
                ('menarche', models.IntegerField(blank=True, null=True, verbose_name='Menarche (Age)')),
                ('sexually_active', models.BooleanField(blank=True, null=True, verbose_name='Sexually Active')),
                ('number_of_partners', models.IntegerField(blank=True, null=True, verbose_name='Number of Partners')),
                ('is_menopause', models.BooleanField(blank=True, null=True, verbose_name='Menopause')),
                ('menopause_age', models.IntegerField(blank=True, null=True, verbose_name='Menopause Age')),
                ('last_menstrual_period', models.DateField(blank=True, null=True, verbose_name='Last Menstrual Period (LMP)')),
                ('period_duration', models.IntegerField(blank=True, null=True, verbose_name='Period Duration (Days)')),
                ('period_interval', models.IntegerField(blank=True, null=True, verbose_name='Period Interval (Days)')),
                ('pads_per_day', models.IntegerField(blank=True, null=True, verbose_name='Pads per Day')),
                ('is_pregnant', models.BooleanField(blank=True, null=True, verbose_name='Is Pregnant')),
                ('gravidity', models.IntegerField(blank=True, null=True, verbose_name='Gravidity')),
                ('parity', models.IntegerField(blank=True, null=True, verbose_name='Parity')),
                ('delivery_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Type of Delivery')),
                ('full_term_births', models.IntegerField(blank=True, null=True, verbose_name='Number of Full Term Births')),
                ('premature_births', models.IntegerField(blank=True, null=True, verbose_name='Number of Premature Births')),
                ('abortions', models.IntegerField(blank=True, null=True, verbose_name='Number of Abortions')),
                ('living_children', models.IntegerField(blank=True, null=True, verbose_name='Number of Living Children')),
                ('disease', models.ForeignKey(blank=True, help_text='Verified disease from database', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='analytics.disease')),
                ('examined_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examinations_performed', to=settings.AUTH_USER_MODEL, verbose_name='Examined By')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='facilities.facility')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referrals.referral')),
            ],
        ),
    ]
