# Generated by Django 5.2 on 2025-05-01 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('bp_systolic', models.IntegerField()),
                ('bp_diastolic', models.IntegerField()),
                ('pulse_rate', models.IntegerField()),
                ('respiratory_rate', models.IntegerField()),
                ('temperature', models.FloatField()),
                ('oxygen_saturation', models.FloatField()),
                ('chief_complaint', models.TextField()),
                ('detailed_symptoms', models.TextField(blank=True)),
                ('work_up_done', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('referring_bhw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
