# Generated by Django 5.2 on 2025-12-18 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='family_planning_type',
            field=models.CharField(blank=True, choices=[('DMPA', 'DMPA'), ('IMPLANT', 'IMPLANT'), ('IUD', 'IUD'), ('PILLS', 'PILLS'), ('CONDOM', 'CONDOM'), ('VASECTOMY', 'VASECTOMY'), ('WITHDRAWAL', 'WITHDRAWAL'), ('NONE', 'NONE')], max_length=20, null=True, verbose_name='Family Planning Type'),
        ),
    ]
