# Generated by Django 5.2 on 2025-05-01 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referral',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='address',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='detailed_symptoms',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='referring_bhw',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='work_up_done',
        ),
        migrations.AddField(
            model_name='referral',
            name='paddress',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referral',
            name='symptoms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='work_up_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='bp_diastolic',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='referral',
            name='bp_systolic',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='referral',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='referral',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='referral',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='referral',
            name='middle_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='referral',
            name='oxygen_saturation',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='referral',
            name='pulse_rate',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='referral',
            name='respiratory_rate',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='referral',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='referral',
            name='temperature',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='referral',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
