# Generated by Django 5.2 on 2025-05-01 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0002_rename_date_created_referral_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='referral',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='referral',
            name='bp_diastolic',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='referral',
            name='bp_systolic',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='referral',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='referral',
            name='height',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='referral',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='referral',
            name='middle_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='referral',
            name='oxygen_saturation',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='referral',
            name='paddress',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='referral',
            name='pulse_rate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='referral',
            name='respiratory_rate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='referral',
            name='sex',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='referral',
            name='symptoms',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='referral',
            name='temperature',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='referral',
            name='weight',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='referral',
            name='work_up_details',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
