# Generated by Django 5.2 on 2025-05-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0003_remove_referral_updated_at_alter_referral_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='pnumber',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
