# Generated by Django 5.2 on 2025-05-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0004_referral_pnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
