# Generated by Django 5.2 on 2025-05-06 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_rename_user_id_patient_user'),
        ('referrals', '0009_referrals_bhw_assigned'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='referral',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='age',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='id',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='paddress',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='pnumber',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='sex',
        ),
        migrations.AddField(
            model_name='referral',
            name='bhw_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referral',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referral',
            name='referral_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='referral',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='referral',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='referral',
            name='oxygen_saturation',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='referral',
            name='temperature',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='referral',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.DeleteModel(
            name='Referrals',
        ),
    ]
