# Generated by Django 5.2 on 2025-05-06 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0010_rename_user_id_referral_user_remove_referral_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='bhw_assigned',
        ),
    ]
