# Generated by Django 5.2 on 2025-05-22 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0011_remove_referral_bhw_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
