# Generated by Django 5.2 on 2025-05-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0012_referral_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
