# Generated by Django 5.2 on 2025-06-24 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0013_referral_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='final_diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='initial_diagnosis',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
