# Generated by Django 5.2 on 2025-08-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0014_referral_final_diagnosis_referral_initial_diagnosis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='rejection_reason',
        ),
        migrations.AddField(
            model_name='referral',
            name='followup_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
