# Generated by Django 5.2 on 2025-08-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0015_remove_referral_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='followup_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
