# Generated by Django 5.2 on 2025-10-23 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0015_medical_history_referral'),
        ('referrals', '0017_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referrallog',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='referrallog',
            name='note',
        ),
        migrations.RemoveField(
            model_name='referrallog',
            name='status_after',
        ),
        migrations.RemoveField(
            model_name='referrallog',
            name='status_before',
        ),
        migrations.RemoveField(
            model_name='referrallog',
            name='user',
        ),
        migrations.AlterField(
            model_name='referrallog',
            name='referral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referrals.referral'),
        ),
        migrations.CreateModel(
            name='FollowUpVisit',
            fields=[
                ('followup_id', models.AutoField(primary_key=True, serialize=False)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bp_systolic', models.IntegerField(blank=True, null=True)),
                ('bp_diastolic', models.IntegerField(blank=True, null=True)),
                ('pulse_rate', models.IntegerField(blank=True, null=True)),
                ('respiratory_rate', models.IntegerField(blank=True, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('oxygen_saturation', models.IntegerField(blank=True, null=True)),
                ('visit_date', models.DateField()),
                ('visit_notes', models.TextField(blank=True, null=True)),
                ('current_symptoms', models.TextField(blank=True, null=True)),
                ('treatment_response', models.TextField(blank=True, null=True)),
                ('new_medications', models.TextField(blank=True, null=True)),
                ('next_followup_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medical_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_visits', to='patients.medical_history')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Follow-up Visit',
                'verbose_name_plural': 'Follow-up Visits',
                'ordering': ['-visit_date'],
            },
        ),
    ]
