# Generated by Django 5.2 on 2025-10-27 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0007_remove_facility_user_id_facility_users'),
        ('referrals', '0018_remove_referrallog_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='facility',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='facilities.facility'),
            preserve_default=False,
        ),
    ]
