# Generated by Django 5.2 on 2025-11-07 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0019_referral_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='ICD_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
