# Generated by Django 5.2 on 2025-11-10 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0020_referral_icd_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='cause',
            field=models.TextField(blank=True, null=True, verbose_name='Cause'),
        ),
        migrations.AddField(
            model_name='referral',
            name='referral_type',
            field=models.CharField(blank=True, choices=[('Emergency', 'Emergency'), ('Urgent', 'Urgent'), ('Routine', 'Routine'), ('Follow-up', 'Follow-up'), ('Preventive', 'Preventive')], max_length=20, null=True, verbose_name='Referral Type'),
        ),
        migrations.AddField(
            model_name='referral',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Remarks'),
        ),
        migrations.AddField(
            model_name='referral',
            name='treatments',
            field=models.TextField(blank=True, null=True, verbose_name='Treatments'),
        ),
    ]
