# Generated by Django 5.2 on 2025-11-10 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0021_referral_cause_referral_referral_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='abortions',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of Abortions'),
        ),
        migrations.AddField(
            model_name='referral',
            name='alcohol_bottles_per_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Alcohol: Bottles per Year'),
        ),
        migrations.AddField(
            model_name='referral',
            name='delivery_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Type of Delivery'),
        ),
        migrations.AddField(
            model_name='referral',
            name='family_planning',
            field=models.BooleanField(default=False, verbose_name='Family Planning'),
        ),
        migrations.AddField(
            model_name='referral',
            name='family_planning_type',
            field=models.CharField(blank=True, choices=[('DMPA', 'DMPA'), ('IMPLANT', 'IMPLANT'), ('IUD', 'IUD'), ('PILLS', 'PILLS')], max_length=20, null=True, verbose_name='Family Planning Type'),
        ),
        migrations.AddField(
            model_name='referral',
            name='full_term_births',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of Full Term Births'),
        ),
        migrations.AddField(
            model_name='referral',
            name='gravidity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Gravidity'),
        ),
        migrations.AddField(
            model_name='referral',
            name='is_alcoholic',
            field=models.BooleanField(default=False, verbose_name='Is Alcoholic'),
        ),
        migrations.AddField(
            model_name='referral',
            name='is_menopause',
            field=models.BooleanField(blank=True, null=True, verbose_name='Menopause'),
        ),
        migrations.AddField(
            model_name='referral',
            name='is_pregnant',
            field=models.BooleanField(blank=True, null=True, verbose_name='Is Pregnant'),
        ),
        migrations.AddField(
            model_name='referral',
            name='is_smoker',
            field=models.BooleanField(default=False, verbose_name='Is Smoker'),
        ),
        migrations.AddField(
            model_name='referral',
            name='last_menstrual_period',
            field=models.DateField(blank=True, null=True, verbose_name='Last Menstrual Period (LMP)'),
        ),
        migrations.AddField(
            model_name='referral',
            name='living_children',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of Living Children'),
        ),
        migrations.AddField(
            model_name='referral',
            name='menarche',
            field=models.IntegerField(blank=True, null=True, verbose_name='Menarche (Age)'),
        ),
        migrations.AddField(
            model_name='referral',
            name='menopause_age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Menopause Age'),
        ),
        migrations.AddField(
            model_name='referral',
            name='number_of_partners',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of Partners'),
        ),
        migrations.AddField(
            model_name='referral',
            name='pads_per_day',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pads per Day'),
        ),
        migrations.AddField(
            model_name='referral',
            name='parity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Parity'),
        ),
        migrations.AddField(
            model_name='referral',
            name='period_duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Period Duration (Days)'),
        ),
        migrations.AddField(
            model_name='referral',
            name='period_interval',
            field=models.IntegerField(blank=True, null=True, verbose_name='Period Interval (Days)'),
        ),
        migrations.AddField(
            model_name='referral',
            name='premature_births',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of Premature Births'),
        ),
        migrations.AddField(
            model_name='referral',
            name='sexually_active',
            field=models.BooleanField(blank=True, null=True, verbose_name='Sexually Active'),
        ),
        migrations.AddField(
            model_name='referral',
            name='smoking_sticks_per_day',
            field=models.IntegerField(blank=True, null=True, verbose_name='Smoking: Sticks/Packs per Day'),
        ),
    ]
