# Generated by Django 5.2 on 2025-11-19 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_key', models.CharField(help_text="Internal key (e.g., 'user_registration_enabled')", max_length=100, unique=True)),
                ('setting_name', models.CharField(help_text="Display name (e.g., 'User Registration Enabled')", max_length=200)),
                ('setting_value', models.TextField(help_text='Current value')),
                ('setting_type', models.CharField(choices=[('boolean', 'Boolean (Yes/No)'), ('integer', 'Integer'), ('string', 'Text'), ('email', 'Email'), ('url', 'URL'), ('password', 'Password (masked)')], default='string', max_length=20)),
                ('description', models.TextField(help_text='Description of what this setting does')),
                ('category', models.CharField(choices=[('User Management', 'User Management'), ('Notifications', 'Notifications'), ('System Behavior', 'System Behavior'), ('Security', 'Security'), ('Email/SMS', 'Email/SMS'), ('Display', 'Display'), ('Feature Flags', 'Feature Flags'), ('System Information', 'System Information')], default='System Behavior', max_length=50)),
                ('is_sensitive', models.BooleanField(default=False, help_text='If True, value will be masked in UI (for passwords/tokens)')),
                ('is_editable', models.BooleanField(default=True, help_text='If False, setting cannot be edited from UI')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_configurations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configurations',
                'ordering': ['category', 'setting_name'],
            },
        ),
    ]
