# Generated by Django 5.2 on 2025-10-26 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_bhwregistered_approved_by_bhwregistration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BHWRegistered',
        ),
    ]
