# Generated by Django 5.2 on 2025-11-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_systemconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='bhwregistration',
            name='registration_certificate',
            field=models.ImageField(blank=True, help_text='Registration Certificate image', null=True, upload_to='registration_certificates/%Y/%m/%d/'),
        ),
    ]
