# Generated by Django 5.2 on 2025-11-19 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_bhwregistration_registration_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bhwregistration',
            name='accreditationNumber',
        ),
        migrations.RemoveField(
            model_name='bhwregistration',
            name='registrationNumber',
        ),
    ]
