# Generated by Django 5.2 on 2025-11-22 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_bhwregistration_accreditationnumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bhwregistration',
            name='accreditation_number',
            field=models.CharField(blank=True, help_text='Format: XX-XXX (e.g., 32-424)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='bhwregistration',
            name='registration_number',
            field=models.CharField(blank=True, help_text='Format: XX-XXX (e.g., 32-424)', max_length=10, null=True),
        ),
    ]
