# Generated by Django 5.2 on 2025-10-26 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_nurses_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nurses',
        ),
    ]
