# Generated by Django 5.2 on 2025-10-26 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_nurses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctors',
        ),
    ]
