# Generated by Django 5.2 on 2025-10-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_doctors_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurses',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
    ]
