# Generated by Django 5.2 on 2025-10-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_nurses_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='bhwregistration',
            name='password1',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bhwregistration',
            name='username',
            field=models.CharField(default=1, max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
