# Generated by Django 5.2 on 2025-10-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_bhwregistration_password1_bhwregistration_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bhwregistration',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='bhwregistration',
            name='username',
        ),
        migrations.AddField(
            model_name='nurses',
            name='nursing_affiliation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='nurses',
            name='nursing_assigned_area',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='nurses',
            name='nursing_certification',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='nurses',
            name='nursing_experience_years',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nurses',
            name='nursing_graduation_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nurses',
            name='nursing_school',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='nurses',
            name='nursing_specialization',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
