# Generated by Django 5.2 on 2025-05-24 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('referrals', '0012_referral_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='referral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='referrals.referral'),
        ),
    ]
