# Generated by Django 5.2 on 2025-01-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(
                choices=[
                    ('referral_sent', 'Referral Sent'),
                    ('referral_completed', 'Referral Completed'),
                    ('referral_accepted', 'Referral Accepted'),
                    ('referral_rejected', 'Referral Rejected')
                ],
                default='referral_sent',
                max_length=20
            ),
        ),
    ]
