# Generated by Django 5.2 on 2025-11-18 06:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medical_History',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('illness_name', models.CharField(max_length=255)),
                ('diagnosed_date', models.DateField()),
                ('notes', models.TextField()),
                ('advice', models.TextField()),
                ('followup_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patients_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('p_address', models.TextField()),
                ('p_number', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField(default=datetime.date.today)),
                ('sex', models.CharField(max_length=15)),
                ('cct_beneficiary', models.BooleanField(default=False, verbose_name='CCT Beneficiary')),
                ('phic_status', models.CharField(blank=True, choices=[('M', 'Member'), ('D', 'Dependent'), ('N', 'N/A')], max_length=1, null=True, verbose_name='PHIC Status')),
                ('civil_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Divorced', 'Divorced'), ('Separated', 'Separated')], max_length=20, null=True, verbose_name='Civil Status')),
                ('is_pwd', models.BooleanField(default=False, verbose_name='Person With Disability')),
                ('sitio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sitio')),
                ('barangay', models.CharField(blank=True, max_length=100, null=True, verbose_name='Barangay')),
                ('philhealth_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='PhilHealth Number')),
                ('philhealth_category', models.CharField(blank=True, choices=[('Sponsored', 'Sponsored'), ('Self Paying', 'Self Paying')], max_length=20, null=True, verbose_name='PhilHealth Category')),
                ('private_company_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Private Company Name')),
                ('is_dependent', models.BooleanField(default=False, verbose_name='Is Dependent')),
                ('dependent_member_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dependent Member Name')),
                ('dependent_member_birthday', models.DateField(blank=True, null=True, verbose_name='Dependent Member Birthday')),
                ('dependent_philhealth_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='Dependent PhilHealth Number')),
                ('family_history_hypertension', models.BooleanField(default=False, verbose_name='Family History: Hypertension')),
                ('family_history_diabetes', models.BooleanField(default=False, verbose_name='Family History: Diabetes')),
                ('family_history_cancer', models.BooleanField(default=False, verbose_name='Family History: Cancer')),
                ('family_history_asthma', models.BooleanField(default=False, verbose_name='Family History: Asthma')),
                ('family_history_epilepsy', models.BooleanField(default=False, verbose_name='Family History: Epilepsy')),
                ('family_history_tuberculosis', models.BooleanField(default=False, verbose_name='Family History: Tuberculosis')),
                ('family_history_others', models.TextField(blank=True, null=True, verbose_name='Family History: Others')),
            ],
        ),
    ]
