# Generated by Django 5.2 on 2025-05-05 09:04

import django.db.models.deletion
from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
        ('patients', '0002_medical_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='bdate',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='facility_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='facilities.facility'),
            preserve_default=False,
        ),
    ]
