# Generated by Django 5.2 on 2025-11-24 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSReminderLog',
            fields=[
                ('reminder_id', models.AutoField(primary_key=True, serialize=False)),
                ('followup_date', models.DateField()),
                ('reminder_type', models.CharField(choices=[('today', 'Today'), ('tomorrow', 'Tomorrow')], max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], default='sent', max_length=20)),
                ('medical_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_reminders', to='patients.medical_history')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_reminders', to='patients.patient')),
            ],
            options={
                'indexes': [models.Index(fields=['patient', 'followup_date', 'reminder_type'], name='patients_sm_patient_6faa07_idx')],
                'unique_together': {('patient', 'followup_date', 'reminder_type')},
            },
        ),
    ]
