# Generated by Django 5.2 on 2025-05-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_bdate_patient_facility_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='bdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
