# Generated by Django 5.2 on 2025-05-05 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_patient_bdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='bdate',
        ),
    ]
