# Generated by Django 5.2 on 2025-05-05 09:13
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_remove_patient_bdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
    ]
