# Generated by Django 5.2 on 2025-05-06 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_remove_medical_history_facility_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='user_id',
            new_name='user',
        ),
    ]
