# Generated by Django 5.2 on 2025-05-10 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0004_remove_facility_user_id'),
        ('patients', '0010_rename_user_id_patient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facilities.facility'),
        ),
    ]
