# Generated by Django 5.2 on 2025-06-20 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_patient_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical_history',
            name='advice',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
