# Generated by Django 5.2 on 2025-08-06 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_medical_history_advice'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical_history',
            name='followup_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
