# Generated by Django 5.2 on 2025-08-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_medical_history_followup_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical_history',
            name='followup_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
