# Generated by Django 5.2 on 2025-08-31 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0014_alter_medical_history_followup_date'),
        ('referrals', '0017_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical_history',
            name='referral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_history', to='referrals.referral'),
        ),
    ]
