# Generated by Django 5.2 on 2025-11-10 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0015_medical_history_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='barangay',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Barangay'),
        ),
        migrations.AddField(
            model_name='patient',
            name='cct_beneficiary',
            field=models.BooleanField(default=False, verbose_name='CCT Beneficiary'),
        ),
        migrations.AddField(
            model_name='patient',
            name='civil_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Divorced', 'Divorced'), ('Separated', 'Separated')], max_length=20, null=True, verbose_name='Civil Status'),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_pwd',
            field=models.BooleanField(default=False, verbose_name='Person With Disability'),
        ),
        migrations.AddField(
            model_name='patient',
            name='phic_status',
            field=models.CharField(blank=True, choices=[('M', 'Member'), ('D', 'Dependent')], max_length=1, null=True, verbose_name='PHIC Status'),
        ),
        migrations.AddField(
            model_name='patient',
            name='sitio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sitio'),
        ),
    ]
