# Generated by Django 5.2 on 2025-11-10 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0016_patient_barangay_patient_cct_beneficiary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='dependent_member_birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Dependent Member Birthday'),
        ),
        migrations.AddField(
            model_name='patient',
            name='dependent_member_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dependent Member Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='dependent_philhealth_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Dependent PhilHealth Number'),
        ),
        migrations.AddField(
            model_name='patient',
            name='family_history_asthma',
            field=models.BooleanField(default=False, verbose_name='Family History: Asthma'),
        ),
        migrations.AddField(
            model_name='patient',
            name='family_history_cancer',
            field=models.BooleanField(default=False, verbose_name='Family History: Cancer'),
        ),
        migrations.AddField(
            model_name='patient',
            name='family_history_diabetes',
            field=models.BooleanField(default=False, verbose_name='Family History: Diabetes'),
        ),
        migrations.AddField(
            model_name='patient',
            name='family_history_epilepsy',
            field=models.BooleanField(default=False, verbose_name='Family History: Epilepsy'),
        ),
        migrations.AddField(
            model_name='patient',
            name='family_history_hypertension',
            field=models.BooleanField(default=False, verbose_name='Family History: Hypertension'),
        ),
        migrations.AddField(
            model_name='patient',
            name='family_history_others',
            field=models.TextField(blank=True, null=True, verbose_name='Family History: Others'),
        ),
        migrations.AddField(
            model_name='patient',
            name='family_history_tuberculosis',
            field=models.BooleanField(default=False, verbose_name='Family History: Tuberculosis'),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_dependent',
            field=models.BooleanField(default=False, verbose_name='Is Dependent'),
        ),
        migrations.AddField(
            model_name='patient',
            name='philhealth_category',
            field=models.CharField(blank=True, choices=[('Sponsored', 'Sponsored'), ('Self Paying', 'Self Paying')], max_length=20, null=True, verbose_name='PhilHealth Category'),
        ),
        migrations.AddField(
            model_name='patient',
            name='philhealth_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='PhilHealth Number'),
        ),
        migrations.AddField(
            model_name='patient',
            name='private_company_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Private Company Name'),
        ),
    ]
